### ISSUE TITLE
Plot networks

### ISSUE THREAD

**Issue by albop** [bloomberg/bqplot#110]
Currently, there is no good library to plot graphs with jupyter/python and I wonder if it would be possible to use the bqplot machinery to do just that (at least when there are not many points).

I did a quick prototype to plot networkx graphs ( https://github.com/albop/backtothetrees/blob/master/bqgraphs.ipynb ) using bqplot and found it very easy. Now I can respond to node click events which makes me very happy ;-)

Things I didn't figured out how to do were:
- implement a way to let the user move the nodes (and keep the edges in sync)
- add arrows to the segments (matplotlib has problems there too)
- label the nodes

Edit: replaced in the issue name networks by graphs. Otherwise it may sound confusing.

**Comment by SylvainCorlay** [comment]
cc @ssunkara

**Comment by ssunkara1** [comment]
@albop This looks great!!! 

1. Moving the nodes will be easy now. We can have drag on the `Scatter` and keep the `Lines` in sync with it. I can write up a quick example for that. 

The easiest way to do this would be to have the drag behavior on `Lines` with markers so that we need not do they sync stuff manually. This is part of the bigger to do, which is to add `Scatter` events to `Lines` with markers. Once we have that it should be very straight forward.

2. Arrows, I am not sure if this will be very quick. We can add another `Scatter` with the Markers as arrows. This angle can be set using the `skew` or `rotation` attribute of the `Scatter`. Again, I will come up with a small example for this.

3. Labeling the nodes will be very easy. You can add `names` attribute to the `Scatter`.

P.S.: Sorry for the late response. :(

**Comment by dmadeka** [comment]
@albop Closed by #483

**Comment by fpom** [comment]
>    Moving the nodes will be easy now. We can have drag on the `Scatter`
>    and keep the `Lines` in sync with it. I can write up a quick example for that.
>    The easiest way to do this would be to have the drag behavior on `Lines`
>    with markers so that we need not do they sync stuff manually. This is part
>    of the bigger to do, which is to add `Scatter` events to `Lines` with markers.
>    Once we have that it should be very straight forward.

Sorry to come back to this old issue, but you say that allowing to drag nodes would be easy to implement. However, it seems that the `bqplot.marks.Graph` does not allow it when nodes are placed using `x` and `y` attributes. I'm wondering if it can be made in this case.

>    Arrows, I am not sure if this will be very quick. We can add another `Scatter`
>    with the Markers as arrows. This angle can be set using the `skew` or `rotation`
>    attribute of the `Scatter`. Again, I will come up with a small example for this.

On this point also, I'd be interesting to know if something has been done also. I know that directed graphs can have arrows, but they are placed in the middle. I'd be interested in adding arrow at the tips of edges (and varied sorts of arrow if possible). I thinks I could do the maths to compute the arrow tips positions and angles, but I'd do it from Python, perhaps we can let D3 do it instead.

Thanks in advance for your answer!
Franck
