### ISSUE TITLE
Provide path to save_png

### ISSUE THREAD

**Issue by dmadeka** [bloomberg/bqplot#442]
@fm75 pointed this out

**Comment by SylvainCorlay** [comment]
I think that this a browser setting.

**Comment by dmadeka** [comment]
What do you mean @SylvainCorlay ?

**Comment by SylvainCorlay** [comment]
Depending on your browser setting, clicking on the download link will trigger the download to the default download directory or prompt a dialog to choose a directory. I don't think that this is something we have control over in JavaScript.

**Comment by pganssle** [comment]
Is there no way to have the JavaScript function return data to a Python function? If there is, changing the `save_png` so that it (optionally) returns a base64-encoded PNG to the Python kernel should allow the user to specify a path.

It might also be good to allow the user to specify a stream that the data can be written to, in case they want to work with the base64-encoded data in the notebook for whatever reason (rather than saving it to a filename and then loading it again).

**Comment by jasongrout** [comment]
> Is there no way to have the JavaScript function return data to a Python function? If there is, changing the save_png so that it (optionally) returns a base64-encoded PNG to the Python kernel should allow the user to specify a path.


FYI, it would have to be an asynchronous save, since the data coming back from python couldn't be processed until the current execution context was finished.

**Comment by rmenegaux** [comment]
Fixed in #554
