### ISSUE TITLE
Zoom does not work with firefox

### ISSUE THREAD

**Issue by PBrockmann** [bloomberg/bqplot#52]
It works well with Google Chrome but not with last Firefox 41.0.2

By the way is there a single zoom feature ?
Look at: http://jsfiddle.net/PBrockmann/oh7wjs45/
same as http://bl.ocks.org/jgbos/9752277, just added changes of cursor to col-resize and row-resize when mouse is over an axis.

**Comment by SylvainCorlay** [comment]
@PBrockmann thanks for reporting, some issues with Firefox were recently reported by @stonebig. I will be looking into it. 

Regarding Panning and zooming, the feature exists:
1. When using the `pyplot` API, we provide a default toolbar for Panning and Zooming
2. In the general case, when using the bqplot object model, you can use the `PanZoom` interaction and specify which scale you want to pan and zoom.

Some examples are available in the [Interaction Layer](https://github.com/bloomberg/bqplot/blob/master/examples/Interaction%20Layer.ipynb) example notebook.

**Comment by PBrockmann** [comment]
Ok, thnaks. Seen the possible definition of a dictionnary for the keyword argument of the PanZoom function: PanZoom(scales={'x': [xs], 'y': [ys]})

But a non declarative pan zoom feature on both axis or on single axis would be easier to use.

**Comment by SylvainCorlay** [comment]
@PBrockmann there is a helper function called `panzoom` which takes returns a `PanZoom` object.  It takes a list of marks and inspects for `x` and `y` scales on those marks.

FYI, the behavior of the panzoom helper function is likely to change.
 - We want to expand the argument and have `*marks`rather than `marks`. Hence we will probably deprecate the current behavior.
 - Another change that we want to make which will only impact people implementing custom mark types extending the ones of bqplot is that the panzoom function will not look for `x` and `y` scales but scales that have `x` and `y` orientation, so that it will work with the `sample` and `count` scales of the Hist for example.
