### ISSUE TITLE
PanZoom looses axis with LogScale

### ISSUE THREAD

**Issue by sigbjorngrini** [bloomberg/bqplot#536]
When I use LogScale with PanZoom I need to hold the cursor at lowest possible value while zooming or else the zoom step seems to be too large and the axis disappear (label and ticks). For instance, I modified this example already used for in another issue:

```Python
from bqplot.interacts import PanZoom
import ipywidgets as widgets
import bqplot as bq
from traitlets import link
from collections import OrderedDict

import numpy as np

buttonWidth = '50px'

x_sc = bq.LinearScale()
y_sc = bq.LogScale()


x_data = np.arange(5, 100)
y_data = x_data ** 2

line_chart = bq.Lines(x=x_data, y=y_data, scales= {'x': x_sc, 'y': y_sc}, 
                       display_legend=True, labels=["line 1", "line 2", "line 3"] )

ax_x = bq.Axis(scale=x_sc)
ax_y = bq.Axis(scale=y_sc, orientation='vertical', tick_format='0.2f')

fig = bq.Figure(marks=[line_chart], axes=[ax_x, ax_y])
fig.layout.width = '95%'

pz = PanZoom(scales={'x': [x_sc], 'y': [y_sc]})
pzx = PanZoom(scales={'x': [x_sc]})
pzy = PanZoom(scales={'y': [y_sc], })

#
zoom_interacts = widgets.ToggleButtons(
                                        options=OrderedDict([
                                            ('xy ', pz), 
                                            ('x ', pzx), 
                                            ('y ', pzy),   
                                            (' ', None)]),
                                            icons = ["arrows", "arrows-h", "arrows-v", "stop"],
                                            tooltips = ["zoom/pan in x & y", "zoom/pan in x only", "zoom/pan in y only", "cancel zoom/pan"]
                                        )
#zoom_interacts.style.button_width = buttonWidth

ResetZoomButton = widgets.Button(
    description='',
    disabled=False,
    button_style='', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Reset zoom',
    icon='arrows-alt'
)

def resetZoom(new):
    # Reset the x and y axes on the figure
    fig.axes[0].scale.min = None
    fig.axes[1].scale.min = None
    fig.axes[0].scale.max = None
    fig.axes[1].scale.max = None  
    
ResetZoomButton.on_click(resetZoom)
ResetZoomButton.layout.width = buttonWidth

link((zoom_interacts, 'value'), (fig, 'interaction'))
widgets.VBox([fig, widgets.HBox([zoom_interacts,ResetZoomButton])], align_self='stretch')
```

Using the y-zoom makes the y axis disappear, except if cursor is at low y values.

Edit, you can get the axis "back" by modifying the min and max value using

```Python
fig.axes[1].scale.max=1e4
fig.axes[1].scale.min=1e1
```

But this is impossible using only the PanZoom when the ticks are gone.

**Comment by ssunkara1** [comment]
Sorry for the late reply. 

The axis issue is happening with `LogScale` because pan-zoom is setting the minimum of the scale to a negative number when you zoom out enough. Once the minimum goes below 0, it does not become positive again. I am looking into why this is happening. So setting the `min` value of the y scale makes sure that this issue doesn't happen.

As you said, it doesn't happen when the mouse is at low values of `y` because, when zooming, the value at the current mouse position is held fixed and hence the minimum value doesn't go below 0. Another way to fix this issue is to have an `observe` function on the `min` attribute of the scale, and set the min of the scale to, eg: `minimum(fig.axes[1].scale.min, 1e-32)`. 

I will let you know when we have a proper fix for this.

**Comment by sigbjorngrini** [comment]
No problem. Thank you for the explanation and suggestion.
