### ISSUE TITLE
Jupytercon'17 Notebooks 

### ISSUE THREAD

**Issue by DougRzz** [bloomberg/bqplot#569]
I've just seen the Jupytercon BQplot presentation on Youtube.  It was excellent.  https://youtu.be/i40d8-Hu4vM

Would it be possible to include the Jupyter Notebooks as presented at Jupytercon'17 in the examples folder in this Github repository? 

Here is a link to the slides:
 https://cdn.oreillystatic.com/en/assets/1/event/271/Building%20interactive%20applications%20and%20dashboards%20in%20the%20Jupyter%20Notebook%20_sponsored%20by%20Bloomberg_%20Presentation.pdf

**Comment by ChakriCherukuri** [comment]
@DougRzz glad to know that you liked our talk. The notebooks we demoed during the talk were built  using Bloomberg proprietary datasets and custom widgets (like DataGrid, Multi Select etc) which are  also Bloomberg proprietary (at least for now). So unfortunately we cannot share the notebooks at this time. 
@rmenegaux maybe your brain example can be shared since it's not using any Bloomberg specific datasets/widgets?

**Comment by DougRzz** [comment]
@ChakriCherukuri i understand.  Thanks for letting me know.

@rmenegaux .Both the brain and curve fitting examples were v nice.

**Comment by dmadeka** [comment]
@DougRzz We stole @rmenegaux's example here - https://github.com/dmadeka/PyDataNYC2017

**Comment by DougRzz** [comment]
@dmadeka  thanks for the link

**Comment by PBrockmann** [comment]
"The notebooks we demoed during the talk were built using Bloomberg proprietary datasets and custom widgets (like DataGrid, Multi Select etc) which are also Bloomberg proprietary (at least for now). So unfortunately we cannot share the notebooks at this time."

---> would be very interested to use DataGrid, Multi Select widgets to build complex dashboard with multiple parameters.

**Comment by BIJINICB** [comment]
im getting errors like there is no module called bgplot_extra. what;s that ??
i couldnt find out the solution thou
