### ISSUE TITLE
BrushIntervalSelector brushing initialized to True

### ISSUE THREAD

**Issue by jasongrout** [bloomberg/bqplot#771]
The `brushing` attribute seems to be initialized to True, but should be False to start with:

```python
from bqplot import LinearScale, Axis, Lines, Figure
from bqplot.interacts import BrushIntervalSelector
import numpy as np

# generate data
prices = np.cumsum(np.random.randn(150, 2).dot([[0.5, 0.4], [0.4, 1.0]]), axis=0) + 100
prices1 = prices[:,0]
prices2 = prices[:,1]
domain = list(range(len(prices1)))

# Build plot
x_scale = LinearScale()
y_scale = LinearScale()
line1 = Lines(x=domain, y=prices1, scales=dict(x=x_scale, y=y_scale))
brush = BrushIntervalSelector(scale=x_scale, marks=[line1])
x_ax = Axis(label='X', scale=x_scale)
y_ax = Axis(label='Y', scale=y_scale, orientation='vertical')
fig1 = Figure(marks=[line1], axes=[x_ax, y_ax], interaction=brush)

# display plot
fig1

```
Then
```
brush.brushing
```
gives True, but should give False.

Furthermore, setting the `.selected` value only displays an updated selection every other time, and it seems that the `.brushing` attribute toggles between True and False:

```
brush.selected = [10, 20] # setting the selected range only displays the new range every other time
```

CC @drbitboy who brought up this issue in Gitter.

**Comment by drbitboy** [comment]
Thanks for this.  I am not sure the behavior is wrong in all cases:  This is an example of programmatically setting the .selected range:  in the case of using the mouse to set the .selected range, .brushing=True indicates [mouse-down] and [dragging-i.e.-still-mouse-down] events, and .brushing=False indicates the terminating [mouse-up] event.   I **think** that mouse-driven design behavior is why we see this every-other-programmatic-change behavior.  Our workaround has been to issue two programmatic changes for every single desired change; also, we have tried fiddling with the .brushing trait; either way, we still don't have it right yet.  More comprehensive documentation of how BrushIntervalSelector actually works might enlighten us how to correctly set .selected programmatically.

**Comment by maartenbreddels** [comment]
It seems the initial brushing=True is caused by https://github.com/bloomberg/bqplot/blob/43f4675d3291559801bc930b779dd4383bc5b259/js/src/BrushSelector.js#L91
Maybe @rmenegaux knows how to avoid it.

There is also something funny going on in https://github.com/bloomberg/bqplot/blob/43f4675d3291559801bc930b779dd4383bc5b259/js/src/BrushSelector.js#L273 in that it sets the selected property again after it is set programmatically (again caused by the trigger in line 91).

(for completeness, https://github.com/bloomberg/bqplot/blob/43f4675d3291559801bc930b779dd4383bc5b259/js/src/BrushSelector.js#L297 is responsible for the 'every other time' behaviour, but I think once the initial issue is tackled this behaviour should be normal as well)

**Comment by rmenegaux** [comment]
So this was indeed a bug, caused by https://github.com/bloomberg/bqplot/blob/43f4675d3291559801bc930b779dd4383bc5b259/js/src/BrushSelector.js#L51-L53

When `selected` is changed, the brush is updated and `brush_start` is called, which in turn changes the `brushing` attribute of the model and saves it. However since the model was already in a changing state, this was causing some undefined behavior (by that I mean behavior I don't understand).

In #775 I just deleted the unnecessary calls to brush-start-move-end for programmatic changes to the brush.

@drbitboy this should make setting `brush.selected` straightforward.
